[workspace]
members = [
    # ABIs
    "abis/market_abi",
    # Contracts
    "contracts/market",
    "contracts/src-20",
    "contracts/token",
    "contracts/pyth-mock",
    "scripts/bako/withdraw_reserves",
    "scripts/bako/update_collaterals",
    "scripts/bako/update_market",
    "scripts/bako/change_market_owner",
]
