[workspace]
members = [
    # ABIs
    "abis/market_abi",
    # Contracts
    "contracts/market",
    "contracts/src-20",
    "contracts/token",
    "contracts/pyth-mock",
    # Libs
    "libs/i256",
]
