/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.94.1
*/

import { Contract, Interface } from "fuels";
import type {
  Provider,
  Account,
  StorageSlot,
  AbstractAddress,
  BigNumberish,
  BN,
  Bytes,
  FunctionFragment,
  InvokeFunction,
} from 'fuels';

import type { Enum, Vec } from "./common";

export enum ErrorInput { AlreadyInitialized = 'AlreadyInitialized', Paused = 'Paused', Unauthorized = 'Unauthorized', InsufficientReserves = 'InsufficientReserves', NotLiquidatable = 'NotLiquidatable', NotForSale = 'NotForSale', TooMuchSlippage = 'TooMuchSlippage', SupplyCapExceeded = 'SupplyCapExceeded', NotCollateralized = 'NotCollateralized', BorrowTooSmall = 'BorrowTooSmall', NotPermitted = 'NotPermitted', InvalidPayment = 'InvalidPayment', UnknownAsset = 'UnknownAsset', DebuggingDisabled = 'DebuggingDisabled', NotYetActive = 'NotYetActive', AlreadyActive = 'AlreadyActive', OracleContractIdNotSet = 'OracleContractIdNotSet' };
export enum ErrorOutput { AlreadyInitialized = 'AlreadyInitialized', Paused = 'Paused', Unauthorized = 'Unauthorized', InsufficientReserves = 'InsufficientReserves', NotLiquidatable = 'NotLiquidatable', NotForSale = 'NotForSale', TooMuchSlippage = 'TooMuchSlippage', SupplyCapExceeded = 'SupplyCapExceeded', NotCollateralized = 'NotCollateralized', BorrowTooSmall = 'BorrowTooSmall', NotPermitted = 'NotPermitted', InvalidPayment = 'InvalidPayment', UnknownAsset = 'UnknownAsset', DebuggingDisabled = 'DebuggingDisabled', NotYetActive = 'NotYetActive', AlreadyActive = 'AlreadyActive', OracleContractIdNotSet = 'OracleContractIdNotSet' };

export type AbsorbCollateralEventInput = { address: AddressInput, asset_id: string, amount: BigNumberish, seize_value: BigNumberish, decimals: BigNumberish };
export type AbsorbCollateralEventOutput = { address: AddressOutput, asset_id: string, amount: BN, seize_value: BN, decimals: number };
export type AddressInput = { bits: string };
export type AddressOutput = AddressInput;
export type BuyCollateralEventInput = { caller: AddressInput, recipient: AddressInput, asset_id: string, amount: BigNumberish, price: BigNumberish };
export type BuyCollateralEventOutput = { caller: AddressOutput, recipient: AddressOutput, asset_id: string, amount: BN, price: BN };
export type CollateralAssetAddedInput = { asset_id: string, configuration: CollateralConfigurationInput };
export type CollateralAssetAddedOutput = { asset_id: string, configuration: CollateralConfigurationOutput };
export type CollateralAssetPausedInput = { asset_id: string };
export type CollateralAssetPausedOutput = CollateralAssetPausedInput;
export type CollateralAssetResumedInput = { asset_id: string };
export type CollateralAssetResumedOutput = CollateralAssetResumedInput;
export type CollateralAssetUpdatedInput = { asset_id: string, configuration: CollateralConfigurationInput };
export type CollateralAssetUpdatedOutput = { asset_id: string, configuration: CollateralConfigurationOutput };
export type CollateralConfigurationInput = { asset_id: string, price_feed_id: string, decimals: BigNumberish, borrow_collateral_factor: BigNumberish, liquidate_collateral_factor: BigNumberish, liquidation_penalty: BigNumberish, supply_cap: BigNumberish, paused: boolean };
export type CollateralConfigurationOutput = { asset_id: string, price_feed_id: string, decimals: number, borrow_collateral_factor: BN, liquidate_collateral_factor: BN, liquidation_penalty: BN, supply_cap: BN, paused: boolean };
export type ContractIdInput = { bits: string };
export type ContractIdOutput = ContractIdInput;
export type I256Input = { value: BigNumberish, negative: boolean };
export type I256Output = { value: BN, negative: boolean };
export type MarketBasicEventInput = { market_basic: MarketBasicsInput };
export type MarketBasicEventOutput = { market_basic: MarketBasicsOutput };
export type MarketBasicsInput = { base_supply_index: BigNumberish, base_borrow_index: BigNumberish, tracking_supply_index: BigNumberish, tracking_borrow_index: BigNumberish, total_supply_base: BigNumberish, total_borrow_base: BigNumberish, last_accrual_time: BigNumberish };
export type MarketBasicsOutput = { base_supply_index: BN, base_borrow_index: BN, tracking_supply_index: BN, tracking_borrow_index: BN, total_supply_base: BN, total_borrow_base: BN, last_accrual_time: BN };
export type MarketConfigurationInput = { governor: AddressInput, pause_guardian: AddressInput, base_token: string, base_token_decimals: BigNumberish, base_token_price_feed_id: string, supply_kink: BigNumberish, borrow_kink: BigNumberish, supply_per_second_interest_rate_slope_low: BigNumberish, supply_per_second_interest_rate_slope_high: BigNumberish, supply_per_second_interest_rate_base: BigNumberish, borrow_per_second_interest_rate_slope_low: BigNumberish, borrow_per_second_interest_rate_slope_high: BigNumberish, borrow_per_second_interest_rate_base: BigNumberish, store_front_price_factor: BigNumberish, base_tracking_index_scale: BigNumberish, base_tracking_supply_speed: BigNumberish, base_tracking_borrow_speed: BigNumberish, base_min_for_rewards: BigNumberish, base_borrow_min: BigNumberish, target_reserves: BigNumberish, debug_step: BigNumberish, fuel_eth_base_asset_id: string };
export type MarketConfigurationOutput = { governor: AddressOutput, pause_guardian: AddressOutput, base_token: string, base_token_decimals: number, base_token_price_feed_id: string, supply_kink: BN, borrow_kink: BN, supply_per_second_interest_rate_slope_low: BN, supply_per_second_interest_rate_slope_high: BN, supply_per_second_interest_rate_base: BN, borrow_per_second_interest_rate_slope_low: BN, borrow_per_second_interest_rate_slope_high: BN, borrow_per_second_interest_rate_base: BN, store_front_price_factor: BN, base_tracking_index_scale: BN, base_tracking_supply_speed: BN, base_tracking_borrow_speed: BN, base_min_for_rewards: BN, base_borrow_min: BN, target_reserves: BN, debug_step: BN, fuel_eth_base_asset_id: string };
export type PauseConfigurationInput = { supply_paused: boolean, withdraw_paused: boolean, absorb_paused: boolean, buy_paused: boolean };
export type PauseConfigurationOutput = PauseConfigurationInput;
export type PauseConfigurationEventInput = { pause_config: PauseConfigurationInput };
export type PauseConfigurationEventOutput = { pause_config: PauseConfigurationOutput };
export type PriceInput = { confidence: BigNumberish, exponent: BigNumberish, price: BigNumberish, publish_time: BigNumberish };
export type PriceOutput = { confidence: BN, exponent: number, price: BN, publish_time: BN };
export type ReservesWithdrawnEventInput = { address: AddressInput, amount: BigNumberish };
export type ReservesWithdrawnEventOutput = { address: AddressOutput, amount: BN };
export type UserBasicInput = { principal: I256Input, base_tracking_index: BigNumberish, base_tracking_accrued: BigNumberish };
export type UserBasicOutput = { principal: I256Output, base_tracking_index: BN, base_tracking_accrued: BN };
export type UserBasicEventInput = { address: AddressInput, user_basic: UserBasicInput };
export type UserBasicEventOutput = { address: AddressOutput, user_basic: UserBasicOutput };
export type UserLiquidatedEventInput = { address: AddressInput, liquidator: AddressInput, base_paid_out: BigNumberish, base_paid_out_value: BigNumberish, total_base: BigNumberish, total_base_value: BigNumberish, decimals: BigNumberish };
export type UserLiquidatedEventOutput = { address: AddressOutput, liquidator: AddressOutput, base_paid_out: BN, base_paid_out_value: BN, total_base: BN, total_base_value: BN, decimals: number };
export type UserSupplyBaseEventInput = { address: AddressInput, supply_amount: BigNumberish, repay_amount: BigNumberish };
export type UserSupplyBaseEventOutput = { address: AddressOutput, supply_amount: BN, repay_amount: BN };
export type UserSupplyCollateralEventInput = { address: AddressInput, asset_id: string, amount: BigNumberish };
export type UserSupplyCollateralEventOutput = { address: AddressOutput, asset_id: string, amount: BN };
export type UserWithdrawBaseEventInput = { address: AddressInput, withdraw_amount: BigNumberish, borrow_amount: BigNumberish };
export type UserWithdrawBaseEventOutput = { address: AddressOutput, withdraw_amount: BN, borrow_amount: BN };
export type UserWithdrawCollateralEventInput = { address: AddressInput, asset_id: string, amount: BigNumberish };
export type UserWithdrawCollateralEventOutput = { address: AddressOutput, asset_id: string, amount: BN };

export type MarketConfigurables = Partial<{
  GOVERNOR: AddressInput;
  PAUSE_GUARDIAN: AddressInput;
  BASE_TOKEN: string;
  BASE_TOKEN_DECIMALS: BigNumberish;
  BASE_TOKEN_PRICE_FEED_ID: string;
  SUPPLY_KINK: BigNumberish;
  BORROW_KINK: BigNumberish;
  SUPPLY_PER_SECOND_INTEREST_RATE_SLOPE_LOW: BigNumberish;
  SUPPLY_PER_SECOND_INTEREST_RATE_SLOPE_HIGH: BigNumberish;
  SUPPLY_PER_SECOND_INTEREST_RATE_BASE: BigNumberish;
  BORROW_PER_SECOND_INTEREST_RATE_SLOPE_LOW: BigNumberish;
  BORROW_PER_SECOND_INTEREST_RATE_SLOPE_HIGH: BigNumberish;
  BORROW_PER_SECOND_INTEREST_RATE_BASE: BigNumberish;
  STORE_FRONT_PRICE_FACTOR: BigNumberish;
  BASE_TRACKING_INDEX_SCALE: BigNumberish;
  BASE_TRACKING_SUPPLY_SPEED: BigNumberish;
  BASE_TRACKING_BORROW_SPEED: BigNumberish;
  BASE_MIN_FOR_REWARDS: BigNumberish;
  BASE_BORROW_MIN: BigNumberish;
  TARGET_RESERVES: BigNumberish;
  DEBUG_STEP: BigNumberish;
  FUEL_ETH_BASE_ASSET_ID: string;
}>;

const abi = {
  "encoding": "1",
  "types": [
    {
      "typeId": 0,
      "type": "()",
      "components": [],
      "typeParameters": null
    },
    {
      "typeId": 1,
      "type": "(_, _)",
      "components": [
        {
          "name": "__tuple_element",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "__tuple_element",
          "type": 35,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 2,
      "type": "b256",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 3,
      "type": "bool",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 4,
      "type": "enum Error",
      "components": [
        {
          "name": "AlreadyInitialized",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "Paused",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "Unauthorized",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "InsufficientReserves",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "NotLiquidatable",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "NotForSale",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "TooMuchSlippage",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "SupplyCapExceeded",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "NotCollateralized",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "BorrowTooSmall",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "NotPermitted",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "InvalidPayment",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "UnknownAsset",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "DebuggingDisabled",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "NotYetActive",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "AlreadyActive",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "OracleContractIdNotSet",
          "type": 0,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 5,
      "type": "generic T",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 6,
      "type": "raw untyped ptr",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 7,
      "type": "struct AbsorbCollateralEvent",
      "components": [
        {
          "name": "address",
          "type": 8,
          "typeArguments": null
        },
        {
          "name": "asset_id",
          "type": 2,
          "typeArguments": null
        },
        {
          "name": "amount",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "seize_value",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "decimals",
          "type": 36,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 8,
      "type": "struct Address",
      "components": [
        {
          "name": "bits",
          "type": 2,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 9,
      "type": "struct BuyCollateralEvent",
      "components": [
        {
          "name": "caller",
          "type": 8,
          "typeArguments": null
        },
        {
          "name": "recipient",
          "type": 8,
          "typeArguments": null
        },
        {
          "name": "asset_id",
          "type": 2,
          "typeArguments": null
        },
        {
          "name": "amount",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "price",
          "type": 35,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 10,
      "type": "struct Bytes",
      "components": [
        {
          "name": "buf",
          "type": 24,
          "typeArguments": null
        },
        {
          "name": "len",
          "type": 37,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 11,
      "type": "struct CollateralAssetAdded",
      "components": [
        {
          "name": "asset_id",
          "type": 2,
          "typeArguments": null
        },
        {
          "name": "configuration",
          "type": 15,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 12,
      "type": "struct CollateralAssetPaused",
      "components": [
        {
          "name": "asset_id",
          "type": 2,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 13,
      "type": "struct CollateralAssetResumed",
      "components": [
        {
          "name": "asset_id",
          "type": 2,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 14,
      "type": "struct CollateralAssetUpdated",
      "components": [
        {
          "name": "asset_id",
          "type": 2,
          "typeArguments": null
        },
        {
          "name": "configuration",
          "type": 15,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 15,
      "type": "struct CollateralConfiguration",
      "components": [
        {
          "name": "asset_id",
          "type": 2,
          "typeArguments": null
        },
        {
          "name": "price_feed_id",
          "type": 2,
          "typeArguments": null
        },
        {
          "name": "decimals",
          "type": 36,
          "typeArguments": null
        },
        {
          "name": "borrow_collateral_factor",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "liquidate_collateral_factor",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "liquidation_penalty",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "supply_cap",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "paused",
          "type": 3,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 16,
      "type": "struct ContractId",
      "components": [
        {
          "name": "bits",
          "type": 2,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 17,
      "type": "struct I256",
      "components": [
        {
          "name": "value",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "negative",
          "type": 3,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 18,
      "type": "struct MarketBasicEvent",
      "components": [
        {
          "name": "market_basic",
          "type": 19,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 19,
      "type": "struct MarketBasics",
      "components": [
        {
          "name": "base_supply_index",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "base_borrow_index",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "tracking_supply_index",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "tracking_borrow_index",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "total_supply_base",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "total_borrow_base",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "last_accrual_time",
          "type": 35,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 20,
      "type": "struct MarketConfiguration",
      "components": [
        {
          "name": "governor",
          "type": 8,
          "typeArguments": null
        },
        {
          "name": "pause_guardian",
          "type": 8,
          "typeArguments": null
        },
        {
          "name": "base_token",
          "type": 2,
          "typeArguments": null
        },
        {
          "name": "base_token_decimals",
          "type": 36,
          "typeArguments": null
        },
        {
          "name": "base_token_price_feed_id",
          "type": 2,
          "typeArguments": null
        },
        {
          "name": "supply_kink",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "borrow_kink",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "supply_per_second_interest_rate_slope_low",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "supply_per_second_interest_rate_slope_high",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "supply_per_second_interest_rate_base",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "borrow_per_second_interest_rate_slope_low",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "borrow_per_second_interest_rate_slope_high",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "borrow_per_second_interest_rate_base",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "store_front_price_factor",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "base_tracking_index_scale",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "base_tracking_supply_speed",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "base_tracking_borrow_speed",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "base_min_for_rewards",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "base_borrow_min",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "target_reserves",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "debug_step",
          "type": 37,
          "typeArguments": null
        },
        {
          "name": "fuel_eth_base_asset_id",
          "type": 2,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 21,
      "type": "struct PauseConfiguration",
      "components": [
        {
          "name": "supply_paused",
          "type": 3,
          "typeArguments": null
        },
        {
          "name": "withdraw_paused",
          "type": 3,
          "typeArguments": null
        },
        {
          "name": "absorb_paused",
          "type": 3,
          "typeArguments": null
        },
        {
          "name": "buy_paused",
          "type": 3,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 22,
      "type": "struct PauseConfigurationEvent",
      "components": [
        {
          "name": "pause_config",
          "type": 21,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 23,
      "type": "struct Price",
      "components": [
        {
          "name": "confidence",
          "type": 37,
          "typeArguments": null
        },
        {
          "name": "exponent",
          "type": 36,
          "typeArguments": null
        },
        {
          "name": "price",
          "type": 37,
          "typeArguments": null
        },
        {
          "name": "publish_time",
          "type": 37,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 24,
      "type": "struct RawBytes",
      "components": [
        {
          "name": "ptr",
          "type": 6,
          "typeArguments": null
        },
        {
          "name": "cap",
          "type": 37,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 25,
      "type": "struct RawVec",
      "components": [
        {
          "name": "ptr",
          "type": 6,
          "typeArguments": null
        },
        {
          "name": "cap",
          "type": 37,
          "typeArguments": null
        }
      ],
      "typeParameters": [
        5
      ]
    },
    {
      "typeId": 26,
      "type": "struct ReservesWithdrawnEvent",
      "components": [
        {
          "name": "address",
          "type": 8,
          "typeArguments": null
        },
        {
          "name": "amount",
          "type": 35,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 27,
      "type": "struct UserBasic",
      "components": [
        {
          "name": "principal",
          "type": 17,
          "typeArguments": null
        },
        {
          "name": "base_tracking_index",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "base_tracking_accrued",
          "type": 35,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 28,
      "type": "struct UserBasicEvent",
      "components": [
        {
          "name": "address",
          "type": 8,
          "typeArguments": null
        },
        {
          "name": "user_basic",
          "type": 27,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 29,
      "type": "struct UserLiquidatedEvent",
      "components": [
        {
          "name": "address",
          "type": 8,
          "typeArguments": null
        },
        {
          "name": "liquidator",
          "type": 8,
          "typeArguments": null
        },
        {
          "name": "base_paid_out",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "base_paid_out_value",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "total_base",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "total_base_value",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "decimals",
          "type": 36,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 30,
      "type": "struct UserSupplyBaseEvent",
      "components": [
        {
          "name": "address",
          "type": 8,
          "typeArguments": null
        },
        {
          "name": "supply_amount",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "repay_amount",
          "type": 35,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 31,
      "type": "struct UserSupplyCollateralEvent",
      "components": [
        {
          "name": "address",
          "type": 8,
          "typeArguments": null
        },
        {
          "name": "asset_id",
          "type": 2,
          "typeArguments": null
        },
        {
          "name": "amount",
          "type": 35,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 32,
      "type": "struct UserWithdrawBaseEvent",
      "components": [
        {
          "name": "address",
          "type": 8,
          "typeArguments": null
        },
        {
          "name": "withdraw_amount",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "borrow_amount",
          "type": 35,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 33,
      "type": "struct UserWithdrawCollateralEvent",
      "components": [
        {
          "name": "address",
          "type": 8,
          "typeArguments": null
        },
        {
          "name": "asset_id",
          "type": 2,
          "typeArguments": null
        },
        {
          "name": "amount",
          "type": 35,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 34,
      "type": "struct Vec",
      "components": [
        {
          "name": "buf",
          "type": 25,
          "typeArguments": [
            {
              "name": "",
              "type": 5,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "len",
          "type": 37,
          "typeArguments": null
        }
      ],
      "typeParameters": [
        5
      ]
    },
    {
      "typeId": 35,
      "type": "u256",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 36,
      "type": "u32",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 37,
      "type": "u64",
      "components": null,
      "typeParameters": null
    }
  ],
  "functions": [
    {
      "inputs": [
        {
          "name": "accounts",
          "type": 34,
          "typeArguments": [
            {
              "name": "",
              "type": 8,
              "typeArguments": null
            }
          ]
        }
      ],
      "name": "absorb",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [],
      "name": "activate_contract",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "configuration",
          "type": 15,
          "typeArguments": null
        }
      ],
      "name": "add_collateral_asset",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "write",
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "account",
          "type": 8,
          "typeArguments": null
        }
      ],
      "name": "available_to_borrow",
      "output": {
        "name": "",
        "type": 35,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "asset",
          "type": 2,
          "typeArguments": null
        }
      ],
      "name": "balance_of",
      "output": {
        "name": "",
        "type": 37,
        "typeArguments": null
      },
      "attributes": null
    },
    {
      "inputs": [
        {
          "name": "asset_id",
          "type": 2,
          "typeArguments": null
        },
        {
          "name": "min_amount",
          "type": 35,
          "typeArguments": null
        },
        {
          "name": "recipient",
          "type": 8,
          "typeArguments": null
        }
      ],
      "name": "buy_collateral",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "payable",
          "arguments": []
        },
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "asset_id",
          "type": 2,
          "typeArguments": null
        },
        {
          "name": "collateral_amount",
          "type": 35,
          "typeArguments": null
        }
      ],
      "name": "collateral_value_to_sell",
      "output": {
        "name": "",
        "type": 35,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [],
      "name": "debug_increment_timestamp",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "utilization",
          "type": 35,
          "typeArguments": null
        }
      ],
      "name": "get_borrow_rate",
      "output": {
        "name": "",
        "type": 35,
        "typeArguments": null
      },
      "attributes": null
    },
    {
      "inputs": [],
      "name": "get_collateral_configurations",
      "output": {
        "name": "",
        "type": 34,
        "typeArguments": [
          {
            "name": "",
            "type": 15,
            "typeArguments": null
          }
        ]
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "asset_id",
          "type": 2,
          "typeArguments": null
        }
      ],
      "name": "get_collateral_reserves",
      "output": {
        "name": "",
        "type": 17,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [],
      "name": "get_configuration",
      "output": {
        "name": "",
        "type": 20,
        "typeArguments": null
      },
      "attributes": null
    },
    {
      "inputs": [],
      "name": "get_market_basics",
      "output": {
        "name": "",
        "type": 19,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "price_feed_id",
          "type": 2,
          "typeArguments": null
        }
      ],
      "name": "get_price",
      "output": {
        "name": "",
        "type": 23,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [],
      "name": "get_reserves",
      "output": {
        "name": "",
        "type": 17,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "utilization",
          "type": 35,
          "typeArguments": null
        }
      ],
      "name": "get_supply_rate",
      "output": {
        "name": "",
        "type": 35,
        "typeArguments": null
      },
      "attributes": null
    },
    {
      "inputs": [
        {
          "name": "account",
          "type": 8,
          "typeArguments": null
        }
      ],
      "name": "get_user_basic",
      "output": {
        "name": "",
        "type": 27,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "address",
          "type": 8,
          "typeArguments": null
        },
        {
          "name": "asset_id",
          "type": 2,
          "typeArguments": null
        }
      ],
      "name": "get_user_collateral",
      "output": {
        "name": "",
        "type": 35,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "account",
          "type": 8,
          "typeArguments": null
        }
      ],
      "name": "get_user_supply_borrow",
      "output": {
        "name": "",
        "type": 1,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [],
      "name": "get_utilization",
      "output": {
        "name": "",
        "type": 35,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "account",
          "type": 8,
          "typeArguments": null
        }
      ],
      "name": "is_liquidatable",
      "output": {
        "name": "",
        "type": 3,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "pause_config",
          "type": 21,
          "typeArguments": null
        }
      ],
      "name": "pause",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "write",
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "asset_id",
          "type": 2,
          "typeArguments": null
        }
      ],
      "name": "pause_collateral_asset",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "asset_id",
          "type": 2,
          "typeArguments": null
        },
        {
          "name": "base_amount",
          "type": 35,
          "typeArguments": null
        }
      ],
      "name": "quote_collateral",
      "output": {
        "name": "",
        "type": 35,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "asset_id",
          "type": 2,
          "typeArguments": null
        }
      ],
      "name": "resume_collateral_asset",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "contract_id",
          "type": 16,
          "typeArguments": null
        }
      ],
      "name": "set_pyth_contract_id",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [],
      "name": "supply_base",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "payable",
          "arguments": []
        },
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [],
      "name": "supply_collateral",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "payable",
          "arguments": []
        },
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "asset_id",
          "type": 2,
          "typeArguments": null
        }
      ],
      "name": "totals_collateral",
      "output": {
        "name": "",
        "type": 35,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "asset_id",
          "type": 2,
          "typeArguments": null
        },
        {
          "name": "configuration",
          "type": 15,
          "typeArguments": null
        }
      ],
      "name": "update_collateral_asset",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "update_data",
          "type": 34,
          "typeArguments": [
            {
              "name": "",
              "type": 10,
              "typeArguments": null
            }
          ]
        }
      ],
      "name": "update_fee",
      "output": {
        "name": "",
        "type": 37,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "update_fee",
          "type": 37,
          "typeArguments": null
        },
        {
          "name": "update_data",
          "type": 34,
          "typeArguments": [
            {
              "name": "",
              "type": 10,
              "typeArguments": null
            }
          ]
        }
      ],
      "name": "update_price_feeds",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "payable",
          "arguments": []
        },
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "amount",
          "type": 35,
          "typeArguments": null
        }
      ],
      "name": "withdraw_base",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "asset_id",
          "type": 2,
          "typeArguments": null
        },
        {
          "name": "amount",
          "type": 35,
          "typeArguments": null
        }
      ],
      "name": "withdraw_collateral",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "to",
          "type": 8,
          "typeArguments": null
        },
        {
          "name": "amount",
          "type": 35,
          "typeArguments": null
        }
      ],
      "name": "withdraw_reserves",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    }
  ],
  "loggedTypes": [
    {
      "logId": "5650517601072614705",
      "loggedType": {
        "name": "",
        "type": 4,
        "typeArguments": []
      }
    },
    {
      "logId": "7659206549590130669",
      "loggedType": {
        "name": "",
        "type": 18,
        "typeArguments": []
      }
    },
    {
      "logId": "3591203286967623281",
      "loggedType": {
        "name": "",
        "type": 7,
        "typeArguments": []
      }
    },
    {
      "logId": "5291237237808257645",
      "loggedType": {
        "name": "",
        "type": 28,
        "typeArguments": []
      }
    },
    {
      "logId": "10580804319558431108",
      "loggedType": {
        "name": "",
        "type": 29,
        "typeArguments": []
      }
    },
    {
      "logId": "17075205356227152605",
      "loggedType": {
        "name": "",
        "type": 22,
        "typeArguments": []
      }
    },
    {
      "logId": "16873461032230770227",
      "loggedType": {
        "name": "",
        "type": 11,
        "typeArguments": []
      }
    },
    {
      "logId": "12201150593867749328",
      "loggedType": {
        "name": "",
        "type": 9,
        "typeArguments": []
      }
    },
    {
      "logId": "5007089152005991246",
      "loggedType": {
        "name": "",
        "type": 12,
        "typeArguments": []
      }
    },
    {
      "logId": "9366109880057078281",
      "loggedType": {
        "name": "",
        "type": 13,
        "typeArguments": []
      }
    },
    {
      "logId": "1940341185534100254",
      "loggedType": {
        "name": "",
        "type": 30,
        "typeArguments": []
      }
    },
    {
      "logId": "7026281871582427040",
      "loggedType": {
        "name": "",
        "type": 31,
        "typeArguments": []
      }
    },
    {
      "logId": "7739866021742362880",
      "loggedType": {
        "name": "",
        "type": 14,
        "typeArguments": []
      }
    },
    {
      "logId": "4305272899477449480",
      "loggedType": {
        "name": "",
        "type": 32,
        "typeArguments": []
      }
    },
    {
      "logId": "8551298967468744576",
      "loggedType": {
        "name": "",
        "type": 33,
        "typeArguments": []
      }
    },
    {
      "logId": "2861643217579627023",
      "loggedType": {
        "name": "",
        "type": 26,
        "typeArguments": []
      }
    }
  ],
  "messagesTypes": [],
  "configurables": [
    {
      "name": "GOVERNOR",
      "configurableType": {
        "name": "",
        "type": 8,
        "typeArguments": []
      },
      "offset": 93240
    },
    {
      "name": "PAUSE_GUARDIAN",
      "configurableType": {
        "name": "",
        "type": 8,
        "typeArguments": []
      },
      "offset": 93272
    },
    {
      "name": "BASE_TOKEN",
      "configurableType": {
        "name": "",
        "type": 2,
        "typeArguments": null
      },
      "offset": 92904
    },
    {
      "name": "BASE_TOKEN_DECIMALS",
      "configurableType": {
        "name": "",
        "type": 36,
        "typeArguments": null
      },
      "offset": 92936
    },
    {
      "name": "BASE_TOKEN_PRICE_FEED_ID",
      "configurableType": {
        "name": "",
        "type": 2,
        "typeArguments": null
      },
      "offset": 92944
    },
    {
      "name": "SUPPLY_KINK",
      "configurableType": {
        "name": "",
        "type": 35,
        "typeArguments": null
      },
      "offset": 93336
    },
    {
      "name": "BORROW_KINK",
      "configurableType": {
        "name": "",
        "type": 35,
        "typeArguments": null
      },
      "offset": 93072
    },
    {
      "name": "SUPPLY_PER_SECOND_INTEREST_RATE_SLOPE_LOW",
      "configurableType": {
        "name": "",
        "type": 35,
        "typeArguments": null
      },
      "offset": 93432
    },
    {
      "name": "SUPPLY_PER_SECOND_INTEREST_RATE_SLOPE_HIGH",
      "configurableType": {
        "name": "",
        "type": 35,
        "typeArguments": null
      },
      "offset": 93400
    },
    {
      "name": "SUPPLY_PER_SECOND_INTEREST_RATE_BASE",
      "configurableType": {
        "name": "",
        "type": 35,
        "typeArguments": null
      },
      "offset": 93368
    },
    {
      "name": "BORROW_PER_SECOND_INTEREST_RATE_SLOPE_LOW",
      "configurableType": {
        "name": "",
        "type": 35,
        "typeArguments": null
      },
      "offset": 93168
    },
    {
      "name": "BORROW_PER_SECOND_INTEREST_RATE_SLOPE_HIGH",
      "configurableType": {
        "name": "",
        "type": 35,
        "typeArguments": null
      },
      "offset": 93136
    },
    {
      "name": "BORROW_PER_SECOND_INTEREST_RATE_BASE",
      "configurableType": {
        "name": "",
        "type": 35,
        "typeArguments": null
      },
      "offset": 93104
    },
    {
      "name": "STORE_FRONT_PRICE_FACTOR",
      "configurableType": {
        "name": "",
        "type": 35,
        "typeArguments": null
      },
      "offset": 93304
    },
    {
      "name": "BASE_TRACKING_INDEX_SCALE",
      "configurableType": {
        "name": "",
        "type": 35,
        "typeArguments": null
      },
      "offset": 93008
    },
    {
      "name": "BASE_TRACKING_SUPPLY_SPEED",
      "configurableType": {
        "name": "",
        "type": 35,
        "typeArguments": null
      },
      "offset": 93040
    },
    {
      "name": "BASE_TRACKING_BORROW_SPEED",
      "configurableType": {
        "name": "",
        "type": 35,
        "typeArguments": null
      },
      "offset": 92976
    },
    {
      "name": "BASE_MIN_FOR_REWARDS",
      "configurableType": {
        "name": "",
        "type": 35,
        "typeArguments": null
      },
      "offset": 92872
    },
    {
      "name": "BASE_BORROW_MIN",
      "configurableType": {
        "name": "",
        "type": 35,
        "typeArguments": null
      },
      "offset": 92840
    },
    {
      "name": "TARGET_RESERVES",
      "configurableType": {
        "name": "",
        "type": 35,
        "typeArguments": null
      },
      "offset": 93464
    },
    {
      "name": "DEBUG_STEP",
      "configurableType": {
        "name": "",
        "type": 37,
        "typeArguments": null
      },
      "offset": 93200
    },
    {
      "name": "FUEL_ETH_BASE_ASSET_ID",
      "configurableType": {
        "name": "",
        "type": 2,
        "typeArguments": null
      },
      "offset": 93208
    }
  ]
};

const storageSlots: StorageSlot[] = [
  {
    "key": "411f67b1bf136f1748de53161729ada89f0b6972b8783bcd860925d7cfddceba",
    "value": "00000000000000000000000000000000000000000000000000038d7ea4c68000"
  },
  {
    "key": "411f67b1bf136f1748de53161729ada89f0b6972b8783bcd860925d7cfddcebb",
    "value": "00000000000000000000000000000000000000000000000000038d7ea4c68000"
  },
  {
    "key": "411f67b1bf136f1748de53161729ada89f0b6972b8783bcd860925d7cfddcebc",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "411f67b1bf136f1748de53161729ada89f0b6972b8783bcd860925d7cfddcebd",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "411f67b1bf136f1748de53161729ada89f0b6972b8783bcd860925d7cfddcebe",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "411f67b1bf136f1748de53161729ada89f0b6972b8783bcd860925d7cfddcebf",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "411f67b1bf136f1748de53161729ada89f0b6972b8783bcd860925d7cfddcec0",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "9e39cce573e16c4eb034ec33f6641ef797822070b45760ef0edafbb57a145b1d",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "c9f05e40a03436c822e78a416687947db653880f61c7e4a00ec4059ee20c3cbd",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "e4e26847100238d6956b2dc2c3f81418d1c06748ea6e7f97bc1c1adb91925ecc",
    "value": "0100000000000000010000000000000001000000000000000100000000000000"
  }
];

export class MarketInterface extends Interface {
  constructor() {
    super(abi);
  }

  declare functions: {
    absorb: FunctionFragment;
    activate_contract: FunctionFragment;
    add_collateral_asset: FunctionFragment;
    available_to_borrow: FunctionFragment;
    balance_of: FunctionFragment;
    buy_collateral: FunctionFragment;
    collateral_value_to_sell: FunctionFragment;
    debug_increment_timestamp: FunctionFragment;
    get_borrow_rate: FunctionFragment;
    get_collateral_configurations: FunctionFragment;
    get_collateral_reserves: FunctionFragment;
    get_configuration: FunctionFragment;
    get_market_basics: FunctionFragment;
    get_price: FunctionFragment;
    get_reserves: FunctionFragment;
    get_supply_rate: FunctionFragment;
    get_user_basic: FunctionFragment;
    get_user_collateral: FunctionFragment;
    get_user_supply_borrow: FunctionFragment;
    get_utilization: FunctionFragment;
    is_liquidatable: FunctionFragment;
    pause: FunctionFragment;
    pause_collateral_asset: FunctionFragment;
    quote_collateral: FunctionFragment;
    resume_collateral_asset: FunctionFragment;
    set_pyth_contract_id: FunctionFragment;
    supply_base: FunctionFragment;
    supply_collateral: FunctionFragment;
    totals_collateral: FunctionFragment;
    update_collateral_asset: FunctionFragment;
    update_fee: FunctionFragment;
    update_price_feeds: FunctionFragment;
    withdraw_base: FunctionFragment;
    withdraw_collateral: FunctionFragment;
    withdraw_reserves: FunctionFragment;
  };
}

export class Market extends Contract {
  static readonly abi = abi;
  static readonly storageSlots = storageSlots;

  declare interface: MarketInterface;
  declare functions: {
    absorb: InvokeFunction<[accounts: Vec<AddressInput>], void>;
    activate_contract: InvokeFunction<[], void>;
    add_collateral_asset: InvokeFunction<[configuration: CollateralConfigurationInput], void>;
    available_to_borrow: InvokeFunction<[account: AddressInput], BN>;
    balance_of: InvokeFunction<[asset: string], BN>;
    buy_collateral: InvokeFunction<[asset_id: string, min_amount: BigNumberish, recipient: AddressInput], void>;
    collateral_value_to_sell: InvokeFunction<[asset_id: string, collateral_amount: BigNumberish], BN>;
    debug_increment_timestamp: InvokeFunction<[], void>;
    get_borrow_rate: InvokeFunction<[utilization: BigNumberish], BN>;
    get_collateral_configurations: InvokeFunction<[], Vec<CollateralConfigurationOutput>>;
    get_collateral_reserves: InvokeFunction<[asset_id: string], I256Output>;
    get_configuration: InvokeFunction<[], MarketConfigurationOutput>;
    get_market_basics: InvokeFunction<[], MarketBasicsOutput>;
    get_price: InvokeFunction<[price_feed_id: string], PriceOutput>;
    get_reserves: InvokeFunction<[], I256Output>;
    get_supply_rate: InvokeFunction<[utilization: BigNumberish], BN>;
    get_user_basic: InvokeFunction<[account: AddressInput], UserBasicOutput>;
    get_user_collateral: InvokeFunction<[address: AddressInput, asset_id: string], BN>;
    get_user_supply_borrow: InvokeFunction<[account: AddressInput], [BN, BN]>;
    get_utilization: InvokeFunction<[], BN>;
    is_liquidatable: InvokeFunction<[account: AddressInput], boolean>;
    pause: InvokeFunction<[pause_config: PauseConfigurationInput], void>;
    pause_collateral_asset: InvokeFunction<[asset_id: string], void>;
    quote_collateral: InvokeFunction<[asset_id: string, base_amount: BigNumberish], BN>;
    resume_collateral_asset: InvokeFunction<[asset_id: string], void>;
    set_pyth_contract_id: InvokeFunction<[contract_id: ContractIdInput], void>;
    supply_base: InvokeFunction<[], void>;
    supply_collateral: InvokeFunction<[], void>;
    totals_collateral: InvokeFunction<[asset_id: string], BN>;
    update_collateral_asset: InvokeFunction<[asset_id: string, configuration: CollateralConfigurationInput], void>;
    update_fee: InvokeFunction<[update_data: Vec<Bytes>], BN>;
    update_price_feeds: InvokeFunction<[update_fee: BigNumberish, update_data: Vec<Bytes>], void>;
    withdraw_base: InvokeFunction<[amount: BigNumberish], void>;
    withdraw_collateral: InvokeFunction<[asset_id: string, amount: BigNumberish], void>;
    withdraw_reserves: InvokeFunction<[to: AddressInput, amount: BigNumberish], void>;
  };

  constructor(
    id: string | AbstractAddress,
    accountOrProvider: Account | Provider,
  ) {
    super(id, abi, accountOrProvider);
  }
}
