/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.94.3
*/

import { Contract, Interface } from "fuels";
import type {
  Provider,
  Account,
  StorageSlot,
  AbstractAddress,
  BigNumberish,
  BN,
  Bytes,
  FunctionFragment,
  InvokeFunction,
} from 'fuels';

import type { Enum, Vec } from "./common";

export enum ErrorInput { AlreadyInitialized = 'AlreadyInitialized', Paused = 'Paused', Unauthorized = 'Unauthorized', InsufficientReserves = 'InsufficientReserves', NotLiquidatable = 'NotLiquidatable', NotForSale = 'NotForSale', TooMuchSlippage = 'TooMuchSlippage', SupplyCapExceeded = 'SupplyCapExceeded', NotCollateralized = 'NotCollateralized', BorrowTooSmall = 'BorrowTooSmall', NotPermitted = 'NotPermitted', InvalidPayment = 'InvalidPayment', UnknownAsset = 'UnknownAsset', DebuggingDisabled = 'DebuggingDisabled', NotYetActive = 'NotYetActive', AlreadyActive = 'AlreadyActive', OracleContractIdNotSet = 'OracleContractIdNotSet' };
export enum ErrorOutput { AlreadyInitialized = 'AlreadyInitialized', Paused = 'Paused', Unauthorized = 'Unauthorized', InsufficientReserves = 'InsufficientReserves', NotLiquidatable = 'NotLiquidatable', NotForSale = 'NotForSale', TooMuchSlippage = 'TooMuchSlippage', SupplyCapExceeded = 'SupplyCapExceeded', NotCollateralized = 'NotCollateralized', BorrowTooSmall = 'BorrowTooSmall', NotPermitted = 'NotPermitted', InvalidPayment = 'InvalidPayment', UnknownAsset = 'UnknownAsset', DebuggingDisabled = 'DebuggingDisabled', NotYetActive = 'NotYetActive', AlreadyActive = 'AlreadyActive', OracleContractIdNotSet = 'OracleContractIdNotSet' };

export type AbsorbCollateralEventInput = { address: AddressInput, asset_id: string, amount: BigNumberish, seize_value: BigNumberish, decimals: BigNumberish };
export type AbsorbCollateralEventOutput = { address: AddressOutput, asset_id: string, amount: BN, seize_value: BN, decimals: number };
export type AddressInput = { bits: string };
export type AddressOutput = AddressInput;
export type BuyCollateralEventInput = { caller: AddressInput, recipient: AddressInput, asset_id: string, amount: BigNumberish, price: BigNumberish };
export type BuyCollateralEventOutput = { caller: AddressOutput, recipient: AddressOutput, asset_id: string, amount: BN, price: BN };
export type CollateralAssetAddedInput = { asset_id: string, configuration: CollateralConfigurationInput };
export type CollateralAssetAddedOutput = { asset_id: string, configuration: CollateralConfigurationOutput };
export type CollateralAssetPausedInput = { asset_id: string };
export type CollateralAssetPausedOutput = CollateralAssetPausedInput;
export type CollateralAssetResumedInput = { asset_id: string };
export type CollateralAssetResumedOutput = CollateralAssetResumedInput;
export type CollateralAssetUpdatedInput = { asset_id: string, configuration: CollateralConfigurationInput };
export type CollateralAssetUpdatedOutput = { asset_id: string, configuration: CollateralConfigurationOutput };
export type CollateralConfigurationInput = { asset_id: string, price_feed_id: string, decimals: BigNumberish, borrow_collateral_factor: BigNumberish, liquidate_collateral_factor: BigNumberish, liquidation_penalty: BigNumberish, supply_cap: BigNumberish, paused: boolean };
export type CollateralConfigurationOutput = { asset_id: string, price_feed_id: string, decimals: number, borrow_collateral_factor: BN, liquidate_collateral_factor: BN, liquidation_penalty: BN, supply_cap: BN, paused: boolean };
export type ContractIdInput = { bits: string };
export type ContractIdOutput = ContractIdInput;
export type I256Input = { value: BigNumberish, negative: boolean };
export type I256Output = { value: BN, negative: boolean };
export type MarketBasicEventInput = { market_basic: MarketBasicsInput };
export type MarketBasicEventOutput = { market_basic: MarketBasicsOutput };
export type MarketBasicsInput = { base_supply_index: BigNumberish, base_borrow_index: BigNumberish, tracking_supply_index: BigNumberish, tracking_borrow_index: BigNumberish, total_supply_base: BigNumberish, total_borrow_base: BigNumberish, last_accrual_time: BigNumberish };
export type MarketBasicsOutput = { base_supply_index: BN, base_borrow_index: BN, tracking_supply_index: BN, tracking_borrow_index: BN, total_supply_base: BN, total_borrow_base: BN, last_accrual_time: BN };
export type MarketConfigurationInput = { governor: AddressInput, pause_guardian: AddressInput, base_token: string, base_token_decimals: BigNumberish, base_token_price_feed_id: string, supply_kink: BigNumberish, borrow_kink: BigNumberish, supply_per_second_interest_rate_slope_low: BigNumberish, supply_per_second_interest_rate_slope_high: BigNumberish, supply_per_second_interest_rate_base: BigNumberish, borrow_per_second_interest_rate_slope_low: BigNumberish, borrow_per_second_interest_rate_slope_high: BigNumberish, borrow_per_second_interest_rate_base: BigNumberish, store_front_price_factor: BigNumberish, base_tracking_index_scale: BigNumberish, base_tracking_supply_speed: BigNumberish, base_tracking_borrow_speed: BigNumberish, base_min_for_rewards: BigNumberish, base_borrow_min: BigNumberish, target_reserves: BigNumberish };
export type MarketConfigurationOutput = { governor: AddressOutput, pause_guardian: AddressOutput, base_token: string, base_token_decimals: number, base_token_price_feed_id: string, supply_kink: BN, borrow_kink: BN, supply_per_second_interest_rate_slope_low: BN, supply_per_second_interest_rate_slope_high: BN, supply_per_second_interest_rate_base: BN, borrow_per_second_interest_rate_slope_low: BN, borrow_per_second_interest_rate_slope_high: BN, borrow_per_second_interest_rate_base: BN, store_front_price_factor: BN, base_tracking_index_scale: BN, base_tracking_supply_speed: BN, base_tracking_borrow_speed: BN, base_min_for_rewards: BN, base_borrow_min: BN, target_reserves: BN };
export type MarketConfigurationEventInput = { market_config: MarketConfigurationInput };
export type MarketConfigurationEventOutput = { market_config: MarketConfigurationOutput };
export type PauseConfigurationInput = { supply_paused: boolean, withdraw_paused: boolean, absorb_paused: boolean, buy_paused: boolean };
export type PauseConfigurationOutput = PauseConfigurationInput;
export type PauseConfigurationEventInput = { pause_config: PauseConfigurationInput };
export type PauseConfigurationEventOutput = { pause_config: PauseConfigurationOutput };
export type PriceInput = { confidence: BigNumberish, exponent: BigNumberish, price: BigNumberish, publish_time: BigNumberish };
export type PriceOutput = { confidence: BN, exponent: number, price: BN, publish_time: BN };
export type PriceDataUpdateInput = { update_fee: BigNumberish, publish_times: Vec<BigNumberish>, price_feed_ids: Vec<string>, update_data: Vec<Bytes> };
export type PriceDataUpdateOutput = { update_fee: BN, publish_times: Vec<BN>, price_feed_ids: Vec<string>, update_data: Vec<Bytes> };
export type ReservesWithdrawnEventInput = { address: AddressInput, amount: BigNumberish };
export type ReservesWithdrawnEventOutput = { address: AddressOutput, amount: BN };
export type UserBasicInput = { principal: I256Input, base_tracking_index: BigNumberish, base_tracking_accrued: BigNumberish };
export type UserBasicOutput = { principal: I256Output, base_tracking_index: BN, base_tracking_accrued: BN };
export type UserBasicEventInput = { address: AddressInput, user_basic: UserBasicInput };
export type UserBasicEventOutput = { address: AddressOutput, user_basic: UserBasicOutput };
export type UserLiquidatedEventInput = { address: AddressInput, liquidator: AddressInput, base_paid_out: BigNumberish, base_paid_out_value: BigNumberish, total_base: BigNumberish, total_base_value: BigNumberish, decimals: BigNumberish };
export type UserLiquidatedEventOutput = { address: AddressOutput, liquidator: AddressOutput, base_paid_out: BN, base_paid_out_value: BN, total_base: BN, total_base_value: BN, decimals: number };
export type UserSupplyBaseEventInput = { address: AddressInput, supply_amount: BigNumberish, repay_amount: BigNumberish };
export type UserSupplyBaseEventOutput = { address: AddressOutput, supply_amount: BN, repay_amount: BN };
export type UserSupplyCollateralEventInput = { address: AddressInput, asset_id: string, amount: BigNumberish };
export type UserSupplyCollateralEventOutput = { address: AddressOutput, asset_id: string, amount: BN };
export type UserWithdrawBaseEventInput = { address: AddressInput, withdraw_amount: BigNumberish, borrow_amount: BigNumberish };
export type UserWithdrawBaseEventOutput = { address: AddressOutput, withdraw_amount: BN, borrow_amount: BN };
export type UserWithdrawCollateralEventInput = { address: AddressInput, asset_id: string, amount: BigNumberish };
export type UserWithdrawCollateralEventOutput = { address: AddressOutput, asset_id: string, amount: BN };

export type MarketConfigurables = Partial<{
  DEBUG_STEP: BigNumberish;
  FUEL_ETH_BASE_ASSET_ID: string;
}>;

const abi = {
  "programType": "contract",
  "specVersion": "1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "()",
      "concreteTypeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
    },
    {
      "type": "(u256, u256)",
      "concreteTypeId": "2770d9f762bf8ec295d5c253193cd2897c893401f1f438769f92d212641ec779",
      "metadataTypeId": 0
    },
    {
      "type": "b256",
      "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
    },
    {
      "type": "bool",
      "concreteTypeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
    },
    {
      "type": "enum market_abi::structs::Error",
      "concreteTypeId": "4e6aabd209068d31558291cfd07cff9366801b052a1767bd0a9eb34bf55e8a0e",
      "metadataTypeId": 1
    },
    {
      "type": "struct events::AbsorbCollateralEvent",
      "concreteTypeId": "31d6845ccbeb9e71f30bf07140659072ce92db76041efd6861d6895dace9e658",
      "metadataTypeId": 4
    },
    {
      "type": "struct events::BuyCollateralEvent",
      "concreteTypeId": "a95331d2168897d0f550d1c4f7fc582926a79b3e825866ecf8c11ef8dfb692c6",
      "metadataTypeId": 5
    },
    {
      "type": "struct events::CollateralAssetAdded",
      "concreteTypeId": "ea2a9368cd82d633fcc3411dbff6c25a78c7ccf550034427221102b74d7926db",
      "metadataTypeId": 6
    },
    {
      "type": "struct events::CollateralAssetPaused",
      "concreteTypeId": "457cc10e18076b4e7a0ccc563fd089b256767bb56a148450f7e58f0d7cbf54ef",
      "metadataTypeId": 7
    },
    {
      "type": "struct events::CollateralAssetResumed",
      "concreteTypeId": "81fb1b4fe81422099de81384a1f433aac8964b267aac0428e6bf423e46b88df9",
      "metadataTypeId": 8
    },
    {
      "type": "struct events::CollateralAssetUpdated",
      "concreteTypeId": "6b698723a311c1005f7846d11d7ce209d68d00c120ee855364c14656ffb5b5a7",
      "metadataTypeId": 9
    },
    {
      "type": "struct events::MarketBasicEvent",
      "concreteTypeId": "6a4af7c6d1aa3fedf33604a44da789ba359bf8f662a56fbc4de9603b8e732291",
      "metadataTypeId": 10
    },
    {
      "type": "struct events::MarketConfigurationEvent",
      "concreteTypeId": "61d1473d8ec7f29c9b7f67ec6b840b973400d6af66df556a4fb5ea9884f780b7",
      "metadataTypeId": 11
    },
    {
      "type": "struct events::PauseConfigurationEvent",
      "concreteTypeId": "ecf750cd9cc44add1b8fc9f1b11bb65d0981711b42c84d20aec21ef32bab7682",
      "metadataTypeId": 12
    },
    {
      "type": "struct events::ReservesWithdrawnEvent",
      "concreteTypeId": "27b6995841bd520fff14deec990e8d66c03d8df59a510fa25e505694b0bc6ebe",
      "metadataTypeId": 13
    },
    {
      "type": "struct events::UserBasicEvent",
      "concreteTypeId": "496e403bcde15a6d2d8a6ac3ae964a1db2145d27464fad7ae2b0dd4390c90c19",
      "metadataTypeId": 14
    },
    {
      "type": "struct events::UserLiquidatedEvent",
      "concreteTypeId": "92d691781932f1848ba9433a9b1c09a97f985b331d88a1a289fc54569161d639",
      "metadataTypeId": 15
    },
    {
      "type": "struct events::UserSupplyBaseEvent",
      "concreteTypeId": "1aed7a0722d2031e0bce0b49bb46e0f91a2237480a9d928eb696c7d1a6d7250c",
      "metadataTypeId": 16
    },
    {
      "type": "struct events::UserSupplyCollateralEvent",
      "concreteTypeId": "61825e22a76ff7a0ca3ce1004c7d128c7844a8dde36cf7ea9077f8a57ef1f88a",
      "metadataTypeId": 17
    },
    {
      "type": "struct events::UserWithdrawBaseEvent",
      "concreteTypeId": "3bbf66e44a782b08497502f3c67b5e181f14ef16755805fd800040f902019de1",
      "metadataTypeId": 18
    },
    {
      "type": "struct events::UserWithdrawCollateralEvent",
      "concreteTypeId": "76ac511aac239f80b30e11716c2a730f0a814ea3acc85a13abb1777519465a4a",
      "metadataTypeId": 19
    },
    {
      "type": "struct i256::I256",
      "concreteTypeId": "2c1b573de37da8020776e36206aa54a3020ad03063bf219d626b6c1cdd82c65d",
      "metadataTypeId": 20
    },
    {
      "type": "struct market_abi::structs::CollateralConfiguration",
      "concreteTypeId": "027212d4a883f4144f8043ef93fee6aa9d766041c7735fa37fae71d45ab6d92d",
      "metadataTypeId": 21
    },
    {
      "type": "struct market_abi::structs::MarketBasics",
      "concreteTypeId": "8f0ca9732dda82407f3d36328a5e4b89421c5f1c404a9568afa856df6efb5802",
      "metadataTypeId": 22
    },
    {
      "type": "struct market_abi::structs::MarketConfiguration",
      "concreteTypeId": "788c494dd193488709eb7174a5299c17819b0c2e68089b18e0474d616080cc9c",
      "metadataTypeId": 23
    },
    {
      "type": "struct market_abi::structs::PauseConfiguration",
      "concreteTypeId": "8ec71ec402ef77ffda0627839b31dd1444fad8b4a95507e86bfa89f0517dbc3d",
      "metadataTypeId": 24
    },
    {
      "type": "struct market_abi::structs::PriceDataUpdate",
      "concreteTypeId": "60b16a7d7d88977a17d1cbc5d1d741c4872c833abbe5cd6eaa5e2d741cd8bf19",
      "metadataTypeId": 25
    },
    {
      "type": "struct market_abi::structs::UserBasic",
      "concreteTypeId": "2878312d8fe9af45fe59b9252d6afa651128c8f755ca8f26ae4d67ede06b8ea1",
      "metadataTypeId": 26
    },
    {
      "type": "struct pyth_interface::data_structures::price::Price",
      "concreteTypeId": "8aba92fff7345309d4313706ed7db3a811609f62da8f0d2859819db43d461ff8",
      "metadataTypeId": 27
    },
    {
      "type": "struct std::address::Address",
      "concreteTypeId": "f597b637c3b0f588fb8d7086c6f4735caa3122b85f0423b82e489f9bb58e2308",
      "metadataTypeId": 28
    },
    {
      "type": "struct std::bytes::Bytes",
      "concreteTypeId": "cdd87b7d12fe505416570c294c884bca819364863efe3bf539245fa18515fbbb",
      "metadataTypeId": 29
    },
    {
      "type": "struct std::contract_id::ContractId",
      "concreteTypeId": "29c10735d33b5159f0c71ee1dbd17b36a3e69e41f00fab0d42e1bd9f428d8a54",
      "metadataTypeId": 31
    },
    {
      "type": "struct std::vec::Vec<struct market_abi::structs::CollateralConfiguration>",
      "concreteTypeId": "135bedc713ecdc7e568f13811c40a9df6a62b44f54789c3f87066e7ccaedcc14",
      "metadataTypeId": 33,
      "typeArguments": [
        "027212d4a883f4144f8043ef93fee6aa9d766041c7735fa37fae71d45ab6d92d"
      ]
    },
    {
      "type": "struct std::vec::Vec<struct std::address::Address>",
      "concreteTypeId": "fc4d04749f58f5bf7fd11c9ed9065b555ad48afcaa1172aaefa952a3a7712160",
      "metadataTypeId": 33,
      "typeArguments": [
        "f597b637c3b0f588fb8d7086c6f4735caa3122b85f0423b82e489f9bb58e2308"
      ]
    },
    {
      "type": "struct std::vec::Vec<struct std::bytes::Bytes>",
      "concreteTypeId": "2601885b27af3627b8910876fc176d900cec2b16ec78c538f5f312e785d915f5",
      "metadataTypeId": 33,
      "typeArguments": [
        "cdd87b7d12fe505416570c294c884bca819364863efe3bf539245fa18515fbbb"
      ]
    },
    {
      "type": "u256",
      "concreteTypeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
    },
    {
      "type": "u64",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
    }
  ],
  "metadataTypes": [
    {
      "type": "(_, _)",
      "metadataTypeId": 0,
      "components": [
        {
          "name": "__tuple_element",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "__tuple_element",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        }
      ]
    },
    {
      "type": "enum market_abi::structs::Error",
      "metadataTypeId": 1,
      "components": [
        {
          "name": "AlreadyInitialized",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "Paused",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "Unauthorized",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "InsufficientReserves",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "NotLiquidatable",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "NotForSale",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "TooMuchSlippage",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "SupplyCapExceeded",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "NotCollateralized",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "BorrowTooSmall",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "NotPermitted",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "InvalidPayment",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "UnknownAsset",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "DebuggingDisabled",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "NotYetActive",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "AlreadyActive",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "OracleContractIdNotSet",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        }
      ]
    },
    {
      "type": "generic T",
      "metadataTypeId": 2
    },
    {
      "type": "raw untyped ptr",
      "metadataTypeId": 3
    },
    {
      "type": "struct events::AbsorbCollateralEvent",
      "metadataTypeId": 4,
      "components": [
        {
          "name": "address",
          "typeId": 28
        },
        {
          "name": "asset_id",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "amount",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "seize_value",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "decimals",
          "typeId": 34
        }
      ]
    },
    {
      "type": "struct events::BuyCollateralEvent",
      "metadataTypeId": 5,
      "components": [
        {
          "name": "caller",
          "typeId": 28
        },
        {
          "name": "recipient",
          "typeId": 28
        },
        {
          "name": "asset_id",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "amount",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "price",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        }
      ]
    },
    {
      "type": "struct events::CollateralAssetAdded",
      "metadataTypeId": 6,
      "components": [
        {
          "name": "asset_id",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "configuration",
          "typeId": 21
        }
      ]
    },
    {
      "type": "struct events::CollateralAssetPaused",
      "metadataTypeId": 7,
      "components": [
        {
          "name": "asset_id",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        }
      ]
    },
    {
      "type": "struct events::CollateralAssetResumed",
      "metadataTypeId": 8,
      "components": [
        {
          "name": "asset_id",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        }
      ]
    },
    {
      "type": "struct events::CollateralAssetUpdated",
      "metadataTypeId": 9,
      "components": [
        {
          "name": "asset_id",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "configuration",
          "typeId": 21
        }
      ]
    },
    {
      "type": "struct events::MarketBasicEvent",
      "metadataTypeId": 10,
      "components": [
        {
          "name": "market_basic",
          "typeId": 22
        }
      ]
    },
    {
      "type": "struct events::MarketConfigurationEvent",
      "metadataTypeId": 11,
      "components": [
        {
          "name": "market_config",
          "typeId": 23
        }
      ]
    },
    {
      "type": "struct events::PauseConfigurationEvent",
      "metadataTypeId": 12,
      "components": [
        {
          "name": "pause_config",
          "typeId": 24
        }
      ]
    },
    {
      "type": "struct events::ReservesWithdrawnEvent",
      "metadataTypeId": 13,
      "components": [
        {
          "name": "address",
          "typeId": 28
        },
        {
          "name": "amount",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        }
      ]
    },
    {
      "type": "struct events::UserBasicEvent",
      "metadataTypeId": 14,
      "components": [
        {
          "name": "address",
          "typeId": 28
        },
        {
          "name": "user_basic",
          "typeId": 26
        }
      ]
    },
    {
      "type": "struct events::UserLiquidatedEvent",
      "metadataTypeId": 15,
      "components": [
        {
          "name": "address",
          "typeId": 28
        },
        {
          "name": "liquidator",
          "typeId": 28
        },
        {
          "name": "base_paid_out",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "base_paid_out_value",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "total_base",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "total_base_value",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "decimals",
          "typeId": 34
        }
      ]
    },
    {
      "type": "struct events::UserSupplyBaseEvent",
      "metadataTypeId": 16,
      "components": [
        {
          "name": "address",
          "typeId": 28
        },
        {
          "name": "supply_amount",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "repay_amount",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        }
      ]
    },
    {
      "type": "struct events::UserSupplyCollateralEvent",
      "metadataTypeId": 17,
      "components": [
        {
          "name": "address",
          "typeId": 28
        },
        {
          "name": "asset_id",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "amount",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        }
      ]
    },
    {
      "type": "struct events::UserWithdrawBaseEvent",
      "metadataTypeId": 18,
      "components": [
        {
          "name": "address",
          "typeId": 28
        },
        {
          "name": "withdraw_amount",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "borrow_amount",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        }
      ]
    },
    {
      "type": "struct events::UserWithdrawCollateralEvent",
      "metadataTypeId": 19,
      "components": [
        {
          "name": "address",
          "typeId": 28
        },
        {
          "name": "asset_id",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "amount",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        }
      ]
    },
    {
      "type": "struct i256::I256",
      "metadataTypeId": 20,
      "components": [
        {
          "name": "value",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "negative",
          "typeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
        }
      ]
    },
    {
      "type": "struct market_abi::structs::CollateralConfiguration",
      "metadataTypeId": 21,
      "components": [
        {
          "name": "asset_id",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "price_feed_id",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "decimals",
          "typeId": 34
        },
        {
          "name": "borrow_collateral_factor",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "liquidate_collateral_factor",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "liquidation_penalty",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "supply_cap",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "paused",
          "typeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
        }
      ]
    },
    {
      "type": "struct market_abi::structs::MarketBasics",
      "metadataTypeId": 22,
      "components": [
        {
          "name": "base_supply_index",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "base_borrow_index",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "tracking_supply_index",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "tracking_borrow_index",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "total_supply_base",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "total_borrow_base",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "last_accrual_time",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        }
      ]
    },
    {
      "type": "struct market_abi::structs::MarketConfiguration",
      "metadataTypeId": 23,
      "components": [
        {
          "name": "governor",
          "typeId": 28
        },
        {
          "name": "pause_guardian",
          "typeId": 28
        },
        {
          "name": "base_token",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "base_token_decimals",
          "typeId": 34
        },
        {
          "name": "base_token_price_feed_id",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "supply_kink",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "borrow_kink",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "supply_per_second_interest_rate_slope_low",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "supply_per_second_interest_rate_slope_high",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "supply_per_second_interest_rate_base",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "borrow_per_second_interest_rate_slope_low",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "borrow_per_second_interest_rate_slope_high",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "borrow_per_second_interest_rate_base",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "store_front_price_factor",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "base_tracking_index_scale",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "base_tracking_supply_speed",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "base_tracking_borrow_speed",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "base_min_for_rewards",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "base_borrow_min",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "target_reserves",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        }
      ]
    },
    {
      "type": "struct market_abi::structs::PauseConfiguration",
      "metadataTypeId": 24,
      "components": [
        {
          "name": "supply_paused",
          "typeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
        },
        {
          "name": "withdraw_paused",
          "typeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
        },
        {
          "name": "absorb_paused",
          "typeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
        },
        {
          "name": "buy_paused",
          "typeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
        }
      ]
    },
    {
      "type": "struct market_abi::structs::PriceDataUpdate",
      "metadataTypeId": 25,
      "components": [
        {
          "name": "update_fee",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "publish_times",
          "typeId": 33,
          "typeArguments": [
            {
              "name": "",
              "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
            }
          ]
        },
        {
          "name": "price_feed_ids",
          "typeId": 33,
          "typeArguments": [
            {
              "name": "",
              "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
            }
          ]
        },
        {
          "name": "update_data",
          "typeId": 33,
          "typeArguments": [
            {
              "name": "",
              "typeId": 29
            }
          ]
        }
      ]
    },
    {
      "type": "struct market_abi::structs::UserBasic",
      "metadataTypeId": 26,
      "components": [
        {
          "name": "principal",
          "typeId": 20
        },
        {
          "name": "base_tracking_index",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "base_tracking_accrued",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        }
      ]
    },
    {
      "type": "struct pyth_interface::data_structures::price::Price",
      "metadataTypeId": 27,
      "components": [
        {
          "name": "confidence",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "exponent",
          "typeId": 34
        },
        {
          "name": "price",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "publish_time",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct std::address::Address",
      "metadataTypeId": 28,
      "components": [
        {
          "name": "bits",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        }
      ]
    },
    {
      "type": "struct std::bytes::Bytes",
      "metadataTypeId": 29,
      "components": [
        {
          "name": "buf",
          "typeId": 30
        },
        {
          "name": "len",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct std::bytes::RawBytes",
      "metadataTypeId": 30,
      "components": [
        {
          "name": "ptr",
          "typeId": 3
        },
        {
          "name": "cap",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct std::contract_id::ContractId",
      "metadataTypeId": 31,
      "components": [
        {
          "name": "bits",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        }
      ]
    },
    {
      "type": "struct std::vec::RawVec",
      "metadataTypeId": 32,
      "components": [
        {
          "name": "ptr",
          "typeId": 3
        },
        {
          "name": "cap",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "typeParameters": [
        2
      ]
    },
    {
      "type": "struct std::vec::Vec",
      "metadataTypeId": 33,
      "components": [
        {
          "name": "buf",
          "typeId": 32,
          "typeArguments": [
            {
              "name": "",
              "typeId": 2
            }
          ]
        },
        {
          "name": "len",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "typeParameters": [
        2
      ]
    },
    {
      "type": "u32",
      "metadataTypeId": 34
    }
  ],
  "functions": [
    {
      "inputs": [
        {
          "name": "accounts",
          "concreteTypeId": "fc4d04749f58f5bf7fd11c9ed9065b555ad48afcaa1172aaefa952a3a7712160"
        },
        {
          "name": "price_data_update",
          "concreteTypeId": "60b16a7d7d88977a17d1cbc5d1d741c4872c833abbe5cd6eaa5e2d741cd8bf19"
        }
      ],
      "name": "absorb",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "payable",
          "arguments": []
        },
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "market_configuration",
          "concreteTypeId": "788c494dd193488709eb7174a5299c17819b0c2e68089b18e0474d616080cc9c"
        }
      ],
      "name": "activate_contract",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "configuration",
          "concreteTypeId": "027212d4a883f4144f8043ef93fee6aa9d766041c7735fa37fae71d45ab6d92d"
        }
      ],
      "name": "add_collateral_asset",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "write",
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "account",
          "concreteTypeId": "f597b637c3b0f588fb8d7086c6f4735caa3122b85f0423b82e489f9bb58e2308"
        }
      ],
      "name": "available_to_borrow",
      "output": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "asset",
          "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        }
      ],
      "name": "balance_of",
      "output": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "attributes": null
    },
    {
      "inputs": [
        {
          "name": "asset_id",
          "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "min_amount",
          "concreteTypeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "recipient",
          "concreteTypeId": "f597b637c3b0f588fb8d7086c6f4735caa3122b85f0423b82e489f9bb58e2308"
        }
      ],
      "name": "buy_collateral",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "payable",
          "arguments": []
        },
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "asset_id",
          "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "collateral_amount",
          "concreteTypeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        }
      ],
      "name": "collateral_value_to_sell",
      "output": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [],
      "name": "debug_increment_timestamp",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "utilization",
          "concreteTypeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        }
      ],
      "name": "get_borrow_rate",
      "output": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [],
      "name": "get_collateral_configurations",
      "output": "135bedc713ecdc7e568f13811c40a9df6a62b44f54789c3f87066e7ccaedcc14",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "asset_id",
          "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        }
      ],
      "name": "get_collateral_reserves",
      "output": "2c1b573de37da8020776e36206aa54a3020ad03063bf219d626b6c1cdd82c65d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [],
      "name": "get_market_basics",
      "output": "8f0ca9732dda82407f3d36328a5e4b89421c5f1c404a9568afa856df6efb5802",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [],
      "name": "get_market_configuration",
      "output": "788c494dd193488709eb7174a5299c17819b0c2e68089b18e0474d616080cc9c",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "price_feed_id",
          "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        }
      ],
      "name": "get_price",
      "output": "8aba92fff7345309d4313706ed7db3a811609f62da8f0d2859819db43d461ff8",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [],
      "name": "get_reserves",
      "output": "2c1b573de37da8020776e36206aa54a3020ad03063bf219d626b6c1cdd82c65d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "utilization",
          "concreteTypeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        }
      ],
      "name": "get_supply_rate",
      "output": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "account",
          "concreteTypeId": "f597b637c3b0f588fb8d7086c6f4735caa3122b85f0423b82e489f9bb58e2308"
        }
      ],
      "name": "get_user_basic",
      "output": "2878312d8fe9af45fe59b9252d6afa651128c8f755ca8f26ae4d67ede06b8ea1",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "address",
          "concreteTypeId": "f597b637c3b0f588fb8d7086c6f4735caa3122b85f0423b82e489f9bb58e2308"
        },
        {
          "name": "asset_id",
          "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        }
      ],
      "name": "get_user_collateral",
      "output": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "account",
          "concreteTypeId": "f597b637c3b0f588fb8d7086c6f4735caa3122b85f0423b82e489f9bb58e2308"
        }
      ],
      "name": "get_user_supply_borrow",
      "output": "2770d9f762bf8ec295d5c253193cd2897c893401f1f438769f92d212641ec779",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [],
      "name": "get_utilization",
      "output": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "account",
          "concreteTypeId": "f597b637c3b0f588fb8d7086c6f4735caa3122b85f0423b82e489f9bb58e2308"
        }
      ],
      "name": "is_liquidatable",
      "output": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "pause_config",
          "concreteTypeId": "8ec71ec402ef77ffda0627839b31dd1444fad8b4a95507e86bfa89f0517dbc3d"
        }
      ],
      "name": "pause",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "write",
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "asset_id",
          "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        }
      ],
      "name": "pause_collateral_asset",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "asset_id",
          "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "base_amount",
          "concreteTypeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        }
      ],
      "name": "quote_collateral",
      "output": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "asset_id",
          "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        }
      ],
      "name": "resume_collateral_asset",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "contract_id",
          "concreteTypeId": "29c10735d33b5159f0c71ee1dbd17b36a3e69e41f00fab0d42e1bd9f428d8a54"
        }
      ],
      "name": "set_pyth_contract_id",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [],
      "name": "supply_base",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "payable",
          "arguments": []
        },
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [],
      "name": "supply_collateral",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "payable",
          "arguments": []
        },
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "asset_id",
          "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        }
      ],
      "name": "totals_collateral",
      "output": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "asset_id",
          "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "configuration",
          "concreteTypeId": "027212d4a883f4144f8043ef93fee6aa9d766041c7735fa37fae71d45ab6d92d"
        }
      ],
      "name": "update_collateral_asset",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "update_data",
          "concreteTypeId": "2601885b27af3627b8910876fc176d900cec2b16ec78c538f5f312e785d915f5"
        }
      ],
      "name": "update_fee",
      "output": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "configuration",
          "concreteTypeId": "788c494dd193488709eb7174a5299c17819b0c2e68089b18e0474d616080cc9c"
        }
      ],
      "name": "update_market_configuration",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "price_data_update",
          "concreteTypeId": "60b16a7d7d88977a17d1cbc5d1d741c4872c833abbe5cd6eaa5e2d741cd8bf19"
        }
      ],
      "name": "update_price_feeds_if_necessary",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "payable",
          "arguments": []
        },
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "amount",
          "concreteTypeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "price_data_update",
          "concreteTypeId": "60b16a7d7d88977a17d1cbc5d1d741c4872c833abbe5cd6eaa5e2d741cd8bf19"
        }
      ],
      "name": "withdraw_base",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "payable",
          "arguments": []
        },
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "asset_id",
          "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "amount",
          "concreteTypeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "price_data_update",
          "concreteTypeId": "60b16a7d7d88977a17d1cbc5d1d741c4872c833abbe5cd6eaa5e2d741cd8bf19"
        }
      ],
      "name": "withdraw_collateral",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "payable",
          "arguments": []
        },
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "to",
          "concreteTypeId": "f597b637c3b0f588fb8d7086c6f4735caa3122b85f0423b82e489f9bb58e2308"
        },
        {
          "name": "amount",
          "concreteTypeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        }
      ],
      "name": "withdraw_reserves",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    }
  ],
  "loggedTypes": [
    {
      "logId": "5650517601072614705",
      "concreteTypeId": "4e6aabd209068d31558291cfd07cff9366801b052a1767bd0a9eb34bf55e8a0e"
    },
    {
      "logId": "7659206549590130669",
      "concreteTypeId": "6a4af7c6d1aa3fedf33604a44da789ba359bf8f662a56fbc4de9603b8e732291"
    },
    {
      "logId": "3591203286967623281",
      "concreteTypeId": "31d6845ccbeb9e71f30bf07140659072ce92db76041efd6861d6895dace9e658"
    },
    {
      "logId": "5291237237808257645",
      "concreteTypeId": "496e403bcde15a6d2d8a6ac3ae964a1db2145d27464fad7ae2b0dd4390c90c19"
    },
    {
      "logId": "10580804319558431108",
      "concreteTypeId": "92d691781932f1848ba9433a9b1c09a97f985b331d88a1a289fc54569161d639"
    },
    {
      "logId": "17075205356227152605",
      "concreteTypeId": "ecf750cd9cc44add1b8fc9f1b11bb65d0981711b42c84d20aec21ef32bab7682"
    },
    {
      "logId": "7048493221525582492",
      "concreteTypeId": "61d1473d8ec7f29c9b7f67ec6b840b973400d6af66df556a4fb5ea9884f780b7"
    },
    {
      "logId": "16873461032230770227",
      "concreteTypeId": "ea2a9368cd82d633fcc3411dbff6c25a78c7ccf550034427221102b74d7926db"
    },
    {
      "logId": "12201150593867749328",
      "concreteTypeId": "a95331d2168897d0f550d1c4f7fc582926a79b3e825866ecf8c11ef8dfb692c6"
    },
    {
      "logId": "5007089152005991246",
      "concreteTypeId": "457cc10e18076b4e7a0ccc563fd089b256767bb56a148450f7e58f0d7cbf54ef"
    },
    {
      "logId": "9366109880057078281",
      "concreteTypeId": "81fb1b4fe81422099de81384a1f433aac8964b267aac0428e6bf423e46b88df9"
    },
    {
      "logId": "1940341185534100254",
      "concreteTypeId": "1aed7a0722d2031e0bce0b49bb46e0f91a2237480a9d928eb696c7d1a6d7250c"
    },
    {
      "logId": "7026281871582427040",
      "concreteTypeId": "61825e22a76ff7a0ca3ce1004c7d128c7844a8dde36cf7ea9077f8a57ef1f88a"
    },
    {
      "logId": "7739866021742362880",
      "concreteTypeId": "6b698723a311c1005f7846d11d7ce209d68d00c120ee855364c14656ffb5b5a7"
    },
    {
      "logId": "4305272899477449480",
      "concreteTypeId": "3bbf66e44a782b08497502f3c67b5e181f14ef16755805fd800040f902019de1"
    },
    {
      "logId": "8551298967468744576",
      "concreteTypeId": "76ac511aac239f80b30e11716c2a730f0a814ea3acc85a13abb1777519465a4a"
    },
    {
      "logId": "2861643217579627023",
      "concreteTypeId": "27b6995841bd520fff14deec990e8d66c03d8df59a510fa25e505694b0bc6ebe"
    }
  ],
  "messagesTypes": [],
  "configurables": [
    {
      "name": "DEBUG_STEP",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "offset": 117312
    },
    {
      "name": "FUEL_ETH_BASE_ASSET_ID",
      "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b",
      "offset": 117320
    }
  ]
};

const storageSlots: StorageSlot[] = [
  {
    "key": "411f67b1bf136f1748de53161729ada89f0b6972b8783bcd860925d7cfddceba",
    "value": "00000000000000000000000000000000000000000000000000038d7ea4c68000"
  },
  {
    "key": "411f67b1bf136f1748de53161729ada89f0b6972b8783bcd860925d7cfddcebb",
    "value": "00000000000000000000000000000000000000000000000000038d7ea4c68000"
  },
  {
    "key": "411f67b1bf136f1748de53161729ada89f0b6972b8783bcd860925d7cfddcebc",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "411f67b1bf136f1748de53161729ada89f0b6972b8783bcd860925d7cfddcebd",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "411f67b1bf136f1748de53161729ada89f0b6972b8783bcd860925d7cfddcebe",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "411f67b1bf136f1748de53161729ada89f0b6972b8783bcd860925d7cfddcebf",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "411f67b1bf136f1748de53161729ada89f0b6972b8783bcd860925d7cfddcec0",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "7b867e531e60dfad72c6b3543afcdc72cf783abc1c4f59c0c55ab5aec5f9d432",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "7b867e531e60dfad72c6b3543afcdc72cf783abc1c4f59c0c55ab5aec5f9d433",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "7b867e531e60dfad72c6b3543afcdc72cf783abc1c4f59c0c55ab5aec5f9d434",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "7b867e531e60dfad72c6b3543afcdc72cf783abc1c4f59c0c55ab5aec5f9d435",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "7b867e531e60dfad72c6b3543afcdc72cf783abc1c4f59c0c55ab5aec5f9d436",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "7b867e531e60dfad72c6b3543afcdc72cf783abc1c4f59c0c55ab5aec5f9d437",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "7b867e531e60dfad72c6b3543afcdc72cf783abc1c4f59c0c55ab5aec5f9d438",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "7b867e531e60dfad72c6b3543afcdc72cf783abc1c4f59c0c55ab5aec5f9d439",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "7b867e531e60dfad72c6b3543afcdc72cf783abc1c4f59c0c55ab5aec5f9d43a",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "7b867e531e60dfad72c6b3543afcdc72cf783abc1c4f59c0c55ab5aec5f9d43b",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "7b867e531e60dfad72c6b3543afcdc72cf783abc1c4f59c0c55ab5aec5f9d43c",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "7b867e531e60dfad72c6b3543afcdc72cf783abc1c4f59c0c55ab5aec5f9d43d",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "7b867e531e60dfad72c6b3543afcdc72cf783abc1c4f59c0c55ab5aec5f9d43e",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "7b867e531e60dfad72c6b3543afcdc72cf783abc1c4f59c0c55ab5aec5f9d43f",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "7b867e531e60dfad72c6b3543afcdc72cf783abc1c4f59c0c55ab5aec5f9d440",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "7b867e531e60dfad72c6b3543afcdc72cf783abc1c4f59c0c55ab5aec5f9d441",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "7b867e531e60dfad72c6b3543afcdc72cf783abc1c4f59c0c55ab5aec5f9d442",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "7b867e531e60dfad72c6b3543afcdc72cf783abc1c4f59c0c55ab5aec5f9d443",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "7b867e531e60dfad72c6b3543afcdc72cf783abc1c4f59c0c55ab5aec5f9d444",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "7b867e531e60dfad72c6b3543afcdc72cf783abc1c4f59c0c55ab5aec5f9d445",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "9e39cce573e16c4eb034ec33f6641ef797822070b45760ef0edafbb57a145b1d",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "c9f05e40a03436c822e78a416687947db653880f61c7e4a00ec4059ee20c3cbd",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "e4e26847100238d6956b2dc2c3f81418d1c06748ea6e7f97bc1c1adb91925ecc",
    "value": "0100000000000000010000000000000001000000000000000100000000000000"
  }
];

export class MarketInterface extends Interface {
  constructor() {
    super(abi);
  }

  declare functions: {
    absorb: FunctionFragment;
    activate_contract: FunctionFragment;
    add_collateral_asset: FunctionFragment;
    available_to_borrow: FunctionFragment;
    balance_of: FunctionFragment;
    buy_collateral: FunctionFragment;
    collateral_value_to_sell: FunctionFragment;
    debug_increment_timestamp: FunctionFragment;
    get_borrow_rate: FunctionFragment;
    get_collateral_configurations: FunctionFragment;
    get_collateral_reserves: FunctionFragment;
    get_market_basics: FunctionFragment;
    get_market_configuration: FunctionFragment;
    get_price: FunctionFragment;
    get_reserves: FunctionFragment;
    get_supply_rate: FunctionFragment;
    get_user_basic: FunctionFragment;
    get_user_collateral: FunctionFragment;
    get_user_supply_borrow: FunctionFragment;
    get_utilization: FunctionFragment;
    is_liquidatable: FunctionFragment;
    pause: FunctionFragment;
    pause_collateral_asset: FunctionFragment;
    quote_collateral: FunctionFragment;
    resume_collateral_asset: FunctionFragment;
    set_pyth_contract_id: FunctionFragment;
    supply_base: FunctionFragment;
    supply_collateral: FunctionFragment;
    totals_collateral: FunctionFragment;
    update_collateral_asset: FunctionFragment;
    update_fee: FunctionFragment;
    update_market_configuration: FunctionFragment;
    update_price_feeds_if_necessary: FunctionFragment;
    withdraw_base: FunctionFragment;
    withdraw_collateral: FunctionFragment;
    withdraw_reserves: FunctionFragment;
  };
}

export class Market extends Contract {
  static readonly abi = abi;
  static readonly storageSlots = storageSlots;

  declare interface: MarketInterface;
  declare functions: {
    absorb: InvokeFunction<[accounts: Vec<AddressInput>, price_data_update: PriceDataUpdateInput], void>;
    activate_contract: InvokeFunction<[market_configuration: MarketConfigurationInput], void>;
    add_collateral_asset: InvokeFunction<[configuration: CollateralConfigurationInput], void>;
    available_to_borrow: InvokeFunction<[account: AddressInput], BN>;
    balance_of: InvokeFunction<[asset: string], BN>;
    buy_collateral: InvokeFunction<[asset_id: string, min_amount: BigNumberish, recipient: AddressInput], void>;
    collateral_value_to_sell: InvokeFunction<[asset_id: string, collateral_amount: BigNumberish], BN>;
    debug_increment_timestamp: InvokeFunction<[], void>;
    get_borrow_rate: InvokeFunction<[utilization: BigNumberish], BN>;
    get_collateral_configurations: InvokeFunction<[], Vec<CollateralConfigurationOutput>>;
    get_collateral_reserves: InvokeFunction<[asset_id: string], I256Output>;
    get_market_basics: InvokeFunction<[], MarketBasicsOutput>;
    get_market_configuration: InvokeFunction<[], MarketConfigurationOutput>;
    get_price: InvokeFunction<[price_feed_id: string], PriceOutput>;
    get_reserves: InvokeFunction<[], I256Output>;
    get_supply_rate: InvokeFunction<[utilization: BigNumberish], BN>;
    get_user_basic: InvokeFunction<[account: AddressInput], UserBasicOutput>;
    get_user_collateral: InvokeFunction<[address: AddressInput, asset_id: string], BN>;
    get_user_supply_borrow: InvokeFunction<[account: AddressInput], [BN, BN]>;
    get_utilization: InvokeFunction<[], BN>;
    is_liquidatable: InvokeFunction<[account: AddressInput], boolean>;
    pause: InvokeFunction<[pause_config: PauseConfigurationInput], void>;
    pause_collateral_asset: InvokeFunction<[asset_id: string], void>;
    quote_collateral: InvokeFunction<[asset_id: string, base_amount: BigNumberish], BN>;
    resume_collateral_asset: InvokeFunction<[asset_id: string], void>;
    set_pyth_contract_id: InvokeFunction<[contract_id: ContractIdInput], void>;
    supply_base: InvokeFunction<[], void>;
    supply_collateral: InvokeFunction<[], void>;
    totals_collateral: InvokeFunction<[asset_id: string], BN>;
    update_collateral_asset: InvokeFunction<[asset_id: string, configuration: CollateralConfigurationInput], void>;
    update_fee: InvokeFunction<[update_data: Vec<Bytes>], BN>;
    update_market_configuration: InvokeFunction<[configuration: MarketConfigurationInput], void>;
    update_price_feeds_if_necessary: InvokeFunction<[price_data_update: PriceDataUpdateInput], void>;
    withdraw_base: InvokeFunction<[amount: BigNumberish, price_data_update: PriceDataUpdateInput], void>;
    withdraw_collateral: InvokeFunction<[asset_id: string, amount: BigNumberish, price_data_update: PriceDataUpdateInput], void>;
    withdraw_reserves: InvokeFunction<[to: AddressInput, amount: BigNumberish], void>;
  };

  constructor(
    id: string | AbstractAddress,
    accountOrProvider: Account | Provider,
  ) {
    super(id, abi, accountOrProvider);
  }
}
