[project]
entry = "main.sw"
license = "Apache-2.0"
name = "market"

[dependencies]
market_abi = { path = "../../abis/market_abi" }
i256 = { path = "../../libs/i256" }
pyth_interface = { git = "https://github.com/pyth-network/pyth-crosschain", rev = "aa9509ccd37cf5dc73fee891a5730c351d15235f" }
