[project]
entry = "main.sw"
license = "Apache-2.0"
name = "market"

# address will be the addres of the proxy contract
[proxy]
enabled = true
address = "0xe1e6fb5fc0d08ebd559d00c0b059438e4ff71d956bff0aebfebe883ea3cfaa1d"

[dependencies]
market_abi = { path = "../../abis/market_abi" }
pyth_interface = { git = "https://github.com/pyth-network/pyth-crosschain", rev = "aa9509ccd37cf5dc73fee891a5730c351d15235f" }
sway_libs = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.24.0" }
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.6.1" }
