[project]
entry = "main.sw"
license = "Apache-2.0"
name = "market"

# address will be the addres of the proxy contract
[proxy]
enabled = true
address = "0x64768a2ab7439771433ec28ffc8a8e0a639a2c732e639a44a56731755b2dd036"

[dependencies]
market_abi = { path = "../../abis/market_abi" }
pyth_interface = { git = "https://github.com/pyth-network/pyth-crosschain", rev = "10e5345ea2e29a5cc43311d43e681cf335e834f3" }
src5 = "0.8.1"
ownership = "0.26.1"
signed_int = "0.26.1"
reentrancy = "0.26.0"
