[project]
entry = "abi.sw"
license = "Apache-2.0"
name = "market_abi"

[dependencies]
i256 = { path = "../../libs/i256" }
pyth_interface = { git = "https://github.com/pyth-network/pyth-crosschain", rev = "aa9509ccd37cf5dc73fee891a5730c351d15235f" }
