[project]
entry = "main.sw"
license = "Apache-2.0"
name = "stork_mock"

# address will be the addres of the proxy contract
[proxy]
enabled = true

[dependencies]
stork_sway_sdk = "0.0.3"
signed_int = "0.26.1"
