name: Swaylend USDT Market (testnet)
ecosystem: fuel
networks:
  - id: 0
    start_block: 11380000
    contracts:
      - name: Market
        address:
        abi_file_path: ./abi/market-abi.json
        handler: ./src/event-handlers.ts
        events:
          - name: CollateralAssetAdded
          - name: CollateralAssetUpdated
          - name: GlobalOracleAddedEvent
          - name: GlobalOracleUpdatedEvent
          - name: AssetOracleAddedEvent
          - name: AssetOracleUpdatedEvent
          - name: UserBasicEvent
          - name: MarketBasicEvent
          - name: UserSupplyCollateralEvent
          - name: UserWithdrawCollateralEvent
          - name: UserSupplyBaseEvent
          - name: UserWithdrawBaseEvent
          - name: AbsorbCollateralEvent
          - name: UserLiquidatedEvent
          - name: BuyCollateralEvent
          - name: ReservesWithdrawnEvent
          - name: PauseConfigurationEvent
          - name: MarketConfigurationEvent
