name: Swaylend USDC Market (testnet)
ecosystem: fuel
networks:
  - id: 0
    start_block: 11380000
    contracts:
      - name: Market
        address: 0x6030cf103746576706d7dcc2ae6f6b32ba0db66907a8f9901a0170de5f06acc0
        abi_file_path: ./abi/market-abi.json
        handler: ./src/event-handlers.ts
        events:
          - name: CollateralAssetAdded
          - name: CollateralAssetUpdated
          - name: CollateralAssetPaused
          - name: CollateralAssetResumed
          - name: UserBasicEvent
          - name: MarketBasicEvent
          - name: UserSupplyCollateralEvent
          - name: UserWithdrawCollateralEvent
          - name: UserSupplyBaseEvent
          - name: UserWithdrawBaseEvent
          - name: AbsorbCollateralEvent
          - name: UserLiquidatedEvent
          - name: BuyCollateralEvent
          - name: ReservesWithdrawnEvent
          - name: PauseConfigurationEvent
          - name: MarketConfigurationEvent
