name: Swaylend USDC Market (testnet)
ecosystem: fuel
networks:
  - id: 0
    start_block: 37000000
    contracts:
      - name: Market
        address: 0x64768a2ab7439771433ec28ffc8a8e0a639a2c732e639a44a56731755b2dd036
        abi_file_path: ./abi/market-abi.json
        handler: ./src/event-handlers.ts
        events:
          - name: CollateralAssetAdded
          - name: CollateralAssetUpdated
          - name: GlobalOracleAddedEvent
          - name: GlobalOracleUpdatedEvent
          - name: AssetOracleAddedEvent
          - name: AssetOracleUpdatedEvent
          - name: UserBasicEvent
          - name: MarketBasicEvent
          - name: UserSupplyCollateralEvent
          - name: UserWithdrawCollateralEvent
          - name: UserSupplyBaseEvent
          - name: UserWithdrawBaseEvent
          - name: AbsorbCollateralEvent
          - name: UserLiquidatedEvent
          - name: BuyCollateralEvent
          - name: ReservesWithdrawnEvent
          - name: PauseConfigurationEvent
          - name: MarketConfigurationEvent
