/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.92.1
  Forc version: 0.61.2
  Fuel-Core version: 0.31.0
*/

import type {
  BigNumberish,
  BN,
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
  StrSlice,
} from 'fuels';

import type { Enum, Vec } from "./common";

export type IdentityInput = Enum<{ Address: AddressInput, ContractId: ContractIdInput }>;
export type IdentityOutput = Enum<{ Address: AddressOutput, ContractId: ContractIdOutput }>;

export type AddressInput = { bits: string };
export type AddressOutput = AddressInput;
export type ContractIdInput = { bits: string };
export type ContractIdOutput = ContractIdInput;
export type PriceInput = { asset_id: string, price: BigNumberish, last_update: BigNumberish };
export type PriceOutput = { asset_id: string, price: BN, last_update: BN };

export type OracleAbiConfigurables = {
  ADMIN: AddressInput;
};

interface OracleAbiInterface extends Interface {
  functions: {
    get_price: FunctionFragment;
    owner: FunctionFragment;
    set_price: FunctionFragment;
    set_prices: FunctionFragment;
  };
}

export class OracleAbi extends Contract {
  interface: OracleAbiInterface;
  functions: {
    get_price: InvokeFunction<[asset_id: string], PriceOutput>;
    owner: InvokeFunction<[], IdentityOutput>;
    set_price: InvokeFunction<[asset_id: string, price: BigNumberish], void>;
    set_prices: InvokeFunction<[prices: Vec<[string, BigNumberish]>], void>;
  };
}
