/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.92.1
  Forc version: 0.61.2
  Fuel-Core version: 0.31.0
*/

import type {
  BigNumberish,
  BN,
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
} from 'fuels';

interface TestProjectAbiInterface extends Interface {
  functions: {
    get: FunctionFragment;
    increment: FunctionFragment;
  };
}

export class TestProjectAbi extends Contract {
  interface: TestProjectAbiInterface;
  functions: {
    get: InvokeFunction<[], BN>;
    increment: InvokeFunction<[amount: BigNumberish], void>;
  };
}
