SELECT timestamp,
    blockDate AS block_date,
    chainId AS chain_id,
    poolAddress AS pool_address,
    underlyingTokenAddress AS underlying_token_address,
    underlyingTokenSymbol AS underlying_token_symbol,
    underlyingTokenPriceUsd AS underlying_token_price_usd,
    availableAmount AS available_amount,
    availableAmountUsd AS available_amount_usd,
    suppliedAmount AS supplied_amount,
    suppliedAmountUsd AS supplied_amount_usd,
    collateralAmount AS collateral_amount,
    collateralAmountUsd AS collateral_amount_usd,
    collateralFactor AS collateral_factor,
    supplyIndex AS supply_index,
    supplyApr AS supply_apr,
    borrowedAmount AS borrowed_amount,
    borrowedAmountUsd AS borrowed_amount_usd,
    borrowIndex AS borrow_index,
    borrowApr AS borrow_apr,
    totalFeesUsd AS total_fees_usd,
    userFeesUsd AS user_fees_usd,
    protocolFeesUsd AS protocol_fees_usd
FROM `CollateralPoolSnapshot_raw`
WHERE timestamp > timestamp('{{timestamp}}')
UNION ALL
SELECT timestamp,
    blockDate AS block_date,
    chainId AS chain_id,
    poolAddress AS pool_address,
    underlyingTokenAddress AS underlying_token_address,
    underlyingTokenSymbol AS underlying_token_symbol,
    underlyingTokenPriceUsd AS underlying_token_price_usd,
    availableAmount AS available_amount,
    availableAmountUsd AS available_amount_usd,
    suppliedAmount AS supplied_amount,
    suppliedAmountUsd AS supplied_amount_usd,
    collateralAmount AS collateral_amount,
    collateralAmountUsd AS collateral_amount_usd,
    collateralFactor AS collateral_factor,
    supplyIndex AS supply_index,
    supplyApr AS supply_apr,
    borrowedAmount AS borrowed_amount,
    borrowedAmountUsd AS borrowed_amount_usd,
    borrowIndex AS borrow_index,
    borrowApr AS borrow_apr,
    totalFeesUsd AS total_fees_usd,
    userFeesUsd AS user_fees_usd,
    protocolFeesUsd AS protocol_fees_usd
FROM `BasePoolSnapshot_raw`
WHERE timestamp > timestamp('{{timestamp}}')