SELECT 
timestamp,
block_date,
chain_id,
pool_address,
underlying_token_address,
underlying_token_symbol,
underlying_token_price_usd,
available_amount,
available_amount_usd,
supplied_amount,
supplied_amount_usd,
non_recursive_supplied_amount,
collateral_amount,
collateral_amount_usd,
collateral_factor,
supply_index,
supply_apr,
borrowed_amount,
borrowed_amount_usd,
borrow_index, 
borrow_apr,
total_fees_usd,
user_fees_usd,
protocol_fees_usd
FROM (
        SELECT id,
            timestamp,
            argMax (blockDate, timestamp) as block_date,
            argMax (chainId, timestamp) as chain_id,
            argMax (poolAddress, timestamp) as pool_address,
            argMax (underlyingTokenAddress, timestamp) as underlying_token_address,
            argMax (underlyingTokenSymbol, timestamp) as underlying_token_symbol,
            argMax (underlyingTokenPriceUsd, timestamp) as underlying_token_price_usd,
            argMax (availableAmount, timestamp) as available_amount,
            argMax (availableAmountUsd, timestamp) as available_amount_usd,
            argMax (suppliedAmount, timestamp) as supplied_amount,
            argMax (suppliedAmountUsd, timestamp) as supplied_amount_usd,
            argMax (nonRecursiveSuppliedAmount, timestamp) as non_recursive_supplied_amount,
            argMax (collateralAmount, timestamp) as collateral_amount,
            argMax (collateralAmountUsd, timestamp) as collateral_amount_usd,
            argMax (collateralFactor, timestamp) as collateral_factor,
            argMax (supplyIndex, timestamp) as supply_index,
            argMax (supplyApr, timestamp) as supply_apr,
            argMax (borrowedAmount, timestamp) as borrowed_amount,
            argMax (borrowedAmountUsd, timestamp) as borrowed_amount_usd,
            argMax (borrowIndex, timestamp) as borrow_index,
            argMax (borrowApr, timestamp) as borrow_apr,
            argMax (totalFeesUsd, timestamp) as total_fees_usd,
            argMax (userFeesUsd, timestamp) as user_fees_usd,
            argMax (protocolFeesUsd, timestamp) as protocol_fees_usd
        FROM `CollateralPoolSnapshot_raw`
        WHERE timestamp > timestamp('{{timestamp}}')
        GROUP BY id,
            timestamp
        UNION ALL
        SELECT id,
            timestamp,
            argMax (blockDate, timestamp) as block_date,
            argMax (chainId, timestamp) as chain_id,
            argMax (poolAddress, timestamp) as pool_address,
            argMax (underlyingTokenAddress, timestamp) as underlying_token_address,
            argMax (underlyingTokenSymbol, timestamp) as underlying_token_symbol,
            argMax (underlyingTokenPriceUsd, timestamp) as underlying_token_price_usd,
            argMax (availableAmount, timestamp) as available_amount,
            argMax (availableAmountUsd, timestamp) as available_amount_usd,
            argMax (suppliedAmount, timestamp) as supplied_amount,
            argMax (suppliedAmountUsd, timestamp) as supplied_amount_usd,
            argMax (nonRecursiveSuppliedAmount, timestamp) as non_recursive_supplied_amount,
            argMax (collateralAmount, timestamp) as collateral_amount,
            argMax (collateralAmountUsd, timestamp) as collateral_amount_usd,
            argMax (collateralFactor, timestamp) as collateral_factor,
            argMax (supplyIndex, timestamp) as supply_index,
            argMax (supplyApr, timestamp) as supply_apr,
            argMax (borrowedAmount, timestamp) as borrowed_amount,
            argMax (borrowedAmountUsd, timestamp) as borrowed_amount_usd,
            argMax (borrowIndex, timestamp) as borrow_index,
            argMax (borrowApr, timestamp) as borrow_apr,
            argMax (totalFeesUsd, timestamp) as total_fees_usd,
            argMax (userFeesUsd, timestamp) as user_fees_usd,
            argMax (protocolFeesUsd, timestamp) as protocol_fees_usd
        FROM `BasePoolSnapshot_raw`
        WHERE timestamp > timestamp('{{timestamp}}')
        GROUP BY id,
            timestamp
    )
ORDER BY timestamp ASC
   