[project]
entry = "main.sw"
license = "Apache-2.0"
name = "redstone_prices_mock"

[dependencies]
redstone = { git = "https://github.com/redstone-finance/redstone-fuel-sdk", tag = "v0.66.2-1" }
sway_libs = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.24.0" }
