name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Fuel toolchain
        run: |
          curl https://install.fuel.network | sh && \
          ~/.fuelup/bin/fuelup toolchain install latest
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.79.0
          targets: wasm32-unknown-unknown
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.3
      - name: Build contracts
        run: ~/.fuelup/bin/forc build --release
      - name: Run contracts tests (FORC)
        run: ~/.fuelup/bin/forc test --release
      - name: Run contracts tests (RUST)
        run: cargo test --release local_tests
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run linter
        run: pnpm lint
      - name: Run Envio codegen
        run: pnpm -r codegen
      - name: Run Indexer tests
        run: pnpm -r test